openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /greet:
    get:
      summary: Retrieve a greeting
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
